// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrzuziqvcinexgesayfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyenV6aXF2Y2luZXhnZXNheWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODg4OTIsImV4cCI6MjA2MTk2NDg5Mn0.XDVsOP9D7pdUOA89ew4DqNA8y9vy8SOROV_NSRRb9Ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);